In [1]:
import torch # requires pytorch
import numpy as np
#import autograd

In [2]:
device = torch.device('cpu')
r_vec = np.repeat([np.random.uniform(low=0.95,high=1.5,size=1000)],3,axis=0)
print(r_vec)

[[1.04420961 1.32244363 1.08841229 ... 1.1380269  1.002112   1.12322866]
 [1.04420961 1.32244363 1.08841229 ... 1.1380269  1.002112   1.12322866]
 [1.04420961 1.32244363 1.08841229 ... 1.1380269  1.002112   1.12322866]]


In [3]:
x = torch.tensor(r_vec, requires_grad=True)#.cuda().detach().requires_grad_()

In [4]:
rr = torch.sqrt(torch.sum(x.pow(2),axis=0))

@torch.enable_grad()
def saito77(r):
    return r.pow(2.5)+ r.pow(3.5)

@torch.enable_grad()
def dsaito77_dr(r):
    return 2.5*r.pow(1.5)+ 3.5*r.pow(2.5)
#y = 1.36e6 * rr.pow(-2.14) + 1.68e8 * rr.pow(-6.13)

In [5]:
Ne=saito77(rr)
#Ne = 1.36e6 * rr**(-2.14) + 1.68e8 * rr**(-6.13)

#print(Ne)

In [6]:
Ne.backward((Ne*0+1))

In [7]:
print(x.grad.data)

tensor([[12.4003, 21.0491, 13.5964,  ..., 15.0171, 11.3211, 14.5846],
        [12.4003, 21.0491, 13.5964,  ..., 15.0171, 11.3211, 14.5846],
        [12.4003, 21.0491, 13.5964,  ..., 15.0171, 11.3211, 14.5846]],
       dtype=torch.float64)


In [8]:
print((dsaito77_dr(rr))*(x[1,:])/rr/x.grad.data)

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]], dtype=torch.float64,
       grad_fn=<DivBackward0>)


In [9]:
r_vec[0,:]

array([1.32892997, 1.10314007, 1.23062735, 1.36074576, 0.98761287,
       1.23963363, 1.39368956, 1.11267323, 1.38213418, 1.16790783,
       1.19139119, 1.48583306, 1.18652945, 1.07026164, 1.4114058 ,
       1.2409792 , 1.47651243, 1.20636067, 1.12495435, 1.39544437,
       1.12711634, 1.20209771, 1.11584807, 1.27772585, 1.24796528,
       1.21092734, 1.1921324 , 1.39591996, 1.10847313, 1.21736649,
       1.22953262, 1.03502322, 1.19638716, 1.24931793, 1.28355973,
       1.22670862, 1.49542181, 1.3631874 , 1.03827092, 1.49045745,
       1.27329867, 1.44075658, 1.29983345, 1.33320655, 1.1824228 ,
       1.09946354, 1.13230738, 1.43877704, 1.07228971, 0.96720565,
       1.00445061, 1.09463648, 1.36243081, 1.45888075, 1.02410656,
       0.95788491, 1.41329506, 1.42505125, 1.27486745, 1.03009233,
       1.00322832, 1.26328449, 1.13283563, 1.30249202, 1.48945187,
       1.39894855, 1.03516332, 0.9882281 , 1.35319025, 1.21805861,
       1.40774241, 1.44035212, 1.36410426, 1.29555879, 0.98885

In [10]:
(x*0+1)

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]], dtype=torch.float64,
       grad_fn=<AddBackward0>)

In [11]:
def saito77(r):
    return 1.36e6 * r**(-2.14) + 1.68e8 * r**(-6.13)


In [12]:
1.3184*np.sqrt(3)

2.283535784698808