In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sunRay import plasmaFreq as pfreq
from sunRay import densityModel as dm
from sunRay import scattering as scat 
import torch

In [14]:
device = torch.device('cuda')
r_vec0 =(torch.randn(3,photon_N).to(device)+3)

# np.repeat([np.random.uniform(low=0.95,high=1.5,size=100000)],3,axis=0)

In [15]:

@torch.enable_grad()
def saito77(r):
    return 1.36e6 * r.pow(-2.14) + 1.68e8 * r.pow(-6.13)

@torch.enable_grad()
def dsaito77_dr(r):
    return - 2.9104e6* r.pow(-3.14) -(1.02984e9* r.pow(-7.13)) 
#y = 1.36e6 * rr.pow(-2.14) + 1.68e8 * rr.pow(-6.13)

In [16]:
r_vec = torch.tensor(r_vec0).to(device)#.cuda().detach().requires_grad_()
# initialize
photon_N = 20
start_r = 1.5; # in solar radii
start_theta = 0.1; # in rad
start_phi  = 0; # in rad

f_ratio  = 1.05
ne_r = dm.saito77 # use leblanc for this calculation 


freq0 = f_ratio * pfreq.omega_pe_r(ne_r,start_r)/(2*np.pi)


<ipython-input-16-37f585d4fe1b>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  r_vec = torch.tensor(r_vec0).to(device)#.cuda().detach().requires_grad_()


In [17]:
dNe_dxyz = pfreq.dNe_dxyz(ne_r,r_vec.detach())

In [18]:
rr = torch.sqrt(torch.sum(r_vec.pow(2),axis=0))

In [23]:
print((dsaito77_dr(rr))*(r_vec)/rr/dNe_dxyz-1)

tensor([[-5.9605e-08,  0.0000e+00, -5.9605e-08, -5.9605e-08, -1.1921e-07,
          0.0000e+00, -1.1921e-07,  0.0000e+00, -5.9605e-08,  0.0000e+00,
          0.0000e+00, -5.9605e-08,  0.0000e+00,  0.0000e+00, -5.9605e-08,
         -1.7881e-07, -1.1921e-07,  1.1921e-07, -5.9605e-08,  1.1921e-07],
        [ 0.0000e+00,  0.0000e+00, -5.9605e-08, -1.1921e-07, -5.9605e-08,
          0.0000e+00, -1.1921e-07,  0.0000e+00, -5.9605e-08,  0.0000e+00,
          0.0000e+00, -5.9605e-08,  0.0000e+00,  1.1921e-07, -1.1921e-07,
         -1.1921e-07, -5.9605e-08,  0.0000e+00, -1.1921e-07,  0.0000e+00],
        [-1.1921e-07,  0.0000e+00, -5.9605e-08, -5.9605e-08, -1.1921e-07,
         -1.1921e-07, -5.9605e-08, -5.9605e-08,  0.0000e+00, -5.9605e-08,
          0.0000e+00,  0.0000e+00, -5.9605e-08,  0.0000e+00, -5.9605e-08,
         -5.9605e-08, -1.1921e-07,  1.1921e-07, -1.1921e-07,  1.1921e-07]],
       device='cuda:0')


In [9]:
r_vec[0,:]

tensor([1.0984, 1.4329, 1.4285,  ..., 1.4093, 1.3075, 1.3109], device='cuda:0',
       dtype=torch.float64)

In [63]:
def saito77(r):
    return 1.36e6 * r**(-2.14) + 1.68e8 * r**(-6.13)


In [12]:
1.3184*np.sqrt(3)

2.283535784698808

In [13]:
(torch.randn(3,photon_N).to(device)+3)

tensor([[1.6987, 1.7241, 3.3486, 1.9669, 3.0752, 4.0978, 2.7877, 3.4168, 1.5573,
         2.4910, 2.6248, 2.5415, 2.6842, 2.4276, 3.6108, 5.1249, 3.2276, 0.1180,
         3.3035, 4.2863],
        [3.1252, 3.8563, 3.1029, 5.3392, 4.5693, 2.4286, 1.9171, 3.3208, 3.9071,
         1.8948, 4.1933, 1.8399, 2.6077, 1.9134, 1.9850, 2.1407, 3.5537, 3.6621,
         5.0335, 3.3095],
        [4.1993, 2.7886, 1.3975, 2.3362, 2.2739, 3.9346, 2.5793, 3.8764, 3.3845,
         3.7550, 3.0300, 1.5278, 3.5628, 3.0894, 2.5789, 2.8471, 4.5467, 3.3548,
         1.4873, 3.1238]], device='cuda:0')